### ISSUE TITLE
Strange behavior when a test method returns Property

### ISSUE THREAD

**Issue by moodmosaic** [hedgehogqa/fsharp-hedgehog-xunit#10]
This runs, but passes (or perhaps doesn't run at all?) even though it should fail:

```c#
[Hedgehog.Xunit.Property]
public Hedgehog.Linq.Property CanUseSelectWithAssertion()
{
    var property =
        from x in ForAll(Gen.Bool)
        select Assert.True(!x);

    return property; // Assume Hedgehog.Xunit will then run the property(?)
}
```

If I just use the core library, it runs, and fails, as it should:

```c#
[Fact]
public void CanUseSelectWithAssertion()
{
    var property =
        from x in ForAll(Gen.Bool)
        select Assert.True(!x);

    property.Check();
}
```

---

Both snippets require the following `using` directives:

```c#
using Xunit;
using Hedgehog.Linq;
using static Hedgehog.Linq.Property;
```

**Comment by dharmaturtle** [comment]
This isn't a use case I currently support - but I think it's possible to support. Would you like it? (Just making sure I don't nerdsnipe myself in case the question was academic.)

**Comment by moodmosaic** [comment]
It would be very nice to have, if it's easy to support it. I first came across this [here](https://twitter.com/ploeh/status/1571821466626260998?t=S9Hg5pxi3MhqWyeygfqW8w).

**Comment by dharmaturtle** [comment]
@TysonMN https://github.com/hedgehogqa/fsharp-hedgehog-xunit/compare/main...wip

I have a pattern of defining a `[<Property>]` test, but it's skipped. However, I invoke it later in a second `[<Fact>]` test - this way I can assert against the `report`. The problematic test is the last one - note the `Wat` comment. I'm available to pair whenever :)

**Comment by TysonMN** [comment]
```fsharp
[<Property(Skip = skipReason)>]
  let ``returning a failing property with external gen fails and shrinks, skipped`` i = property {
    // let! a = Gen.int32 (Range.constant 1 100) // uncomment this line to make the test pass. Wat.
    Assert.True(i <= 50)
  }
```

Is this test skipped?

**Comment by dharmaturtle** [comment]
Yes, because if it were really run by XUnit it would fail, which is not desirable. Instead, it is run by the subsequent test annotated with `[<Fact>]` - ` ``returning a failing property with external gen fails and shrinks`` `.

The line `nameof ``returning a failing property with external gen fails and shrinks, skipped`` |> getMethod` returns the test method which I ship off to my "internal logic" to generate a `report` for.

**Comment by TysonMN** [comment]
Ok. I think I understand now.

To repeat back to you:

You want to test what happens when another test fails, so you write such a failing test but skip it and then analyze it in another test.

In this case, your test that intentionally fails but is skipped starts on line 673.  The test that analyzes that test starts on line 678.

Finally, the test starting on line 678 fails but passes if the code on line 674 is commented in.

Did I get that all correct?

**Comment by dharmaturtle** [comment]
Yep!

**Comment by TysonMN** [comment]
I understand the problem.

There are two things that seem wrong to me.

First,
```fsharp
property { failwith "" } |> Property.report
```
throws an exception.  I could look into fixing this, but it doesn't seem worth it.  Why would someone use a `property` CE without a `let!`?

Second, what you are doing doesn't make sense (partly because you are using a `property` CE without a `let!`).  Since no `let!` is needed (in this imagined use case), I think the body of your intentionally failing test should just be
```fsharp
Assert.True(i <= 50)
```

Then your intentionally failing test fails and the corresponding test passes.

@moodmosaic's use case is that `Unit` is the only argument to the test method, the `Property` is fully defined by the user, and then it is returned by the test method, which should simply call `Property.check` on it.

IIRC, the current use case covered by this library is for the user to define a test method like

```fsharp
  [<Property>]
  let myTest i = f i
```

and have it be converted to

```fsharp
property {
    let! i = some generator of the correct type
    f i
}
|> Property.check
```

What doesn't make sense to me is to have both
1. a non-`Unit` parameter in the test method and
2. the user to define their own property.

It is probably possible to make that work, but I don't think it is a good design (to mix/combine these two approaches).  Maybe I am wrong about that though.  I am willing to be listen to an opposing argument.

**Comment by TysonMN** [comment]
Can you create a release with this change?

**Comment by moodmosaic** [comment]
Can't wait to try this! Thank you 👍
